# Site settings
author: Arrington Perry
title: 
header-img: img/home-bg.png
email: perryceo21@hotmail.com
copyright_name: Arrington Perry
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zerocool3089

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
